### ISSUE TITLE
Keyword Filter

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#111]
Do we want the keyword filter to affect the current view it's on?

**Comment by sslampa** [comment]
I won't open another issue for this, but how are we going to test for location? Location just returns everything.

**Comment by suzmas** [comment]
- Keyword filter: yes, affect current view.
  - Location test: search San Diego- if any results are returned, we can take that as verification that location search works.
    - We can potentially make this test more specific later, but for now I don't think it's a priority. Geocoder gem also comes with some default testing- I'll look into it more today.
