### ISSUE TITLE
Map is gone on small screens

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#152]
*2)* I'm not sure if you already fixed the map issues... but that's an issue we'll have to figure out. The map just goes away on small screens

**Comment by sslampa** [comment]
I was able to replicate this. Now that most of the elements are set, we should start looking into the kinds of screen sizes we want to support before rushing to fixing this problem. Thoughts?

**Comment by suzmas** [comment]
Alrighty so I'm checking out Bootstrap's breakpoints. Lord knows what's going on with these components.. they're currently setup to switch to full-width on small screens ( <= 768px ) but I'm looking at it right now, and I'm seeing a resize at 992px. 🙄  

Anywhoooo I'm sure this will be a joy to deal with 😁  ! As far as options for small screen... I know we already have a boatload of buttons in the nav... but we could consider a setup like AirBnb or Yelp.

Consider the ability to switch back to list view: 
 
![image](https://user-images.githubusercontent.com/22352077/26908132-9070dd26-4bad-11e7-85ee-807150eb9fc8.png)

**Comment by sslampa** [comment]
That looks good. Is this how it would default look for larger screens too? Or are we only looking for certain breakpoints?

**Comment by suzmas** [comment]
I don't think it would make sense to do it like this for large screens. it's a mobile thing.

**Comment by sslampa** [comment]
I'm just curious, but can React detect screen size and adjust to views accordingly?

**Comment by suzmas** [comment]
You can get the size of the window via any js

**Comment by sslampa** [comment]
It still doesn't look great, but it works for the most part. Let me know what you think about it so far.
