### ISSUE TITLE
Show events on the current page (of pagination)

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#153]
*3)* Were we going to just show the events on the current page (of pagination) or not?

**Comment by sslampa** [comment]
I'm still not sure if we should show the Places for each event on the page. But again, if you think it's a better way of doing it, I'm all for it.

**Comment by suzmas** [comment]
I think that makes more sense in the interest of consistency. It's weird if the Places view shows markers based on pagination, but then when you view the events, there are suddenly like 20 markers. Plus, consider if there a ton of places and they're _all_ on the map. 

I dunno what you think would be easiest here- lmk. We could add a lat/lng attribute to event objects
