### ISSUE TITLE
Place model spec fails

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#154]
*5)* I don't know exactly what the deal is with this but the full address spec randomly fails

**Comment by sslampa** [comment]
I just made the test to be general. Since you've made it so that the model has to return something, making sure it's not nil should be good enough. Let me know what you think.

**Comment by suzmas** [comment]
Sounds good. I'll look into a little further just in case. It's something with the neighborhood data changing... Both returns are valid so it's not a huge deal... but... inquiring minds would like to know.

Closing this out.
