### ISSUE TITLE
Bug: Markers are shown to be active when panel is untoggled

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#161]

**Comment by sslampa** [comment]
I ran out of ideas for this one, so I would appreciate any help

**Comment by suzmas** [comment]
It's only happening when another panel is selected without the active panel being purposely closed... so it's something with the toggling callback- looks like something got jumbled when the event listener for the default toggle behavior was removed. 

I haven't looked at the updated code for this- but I _think_ I had a listener for the event that's fired by React-Bootstrap. Potentially just add another event listener for that (assuming the way you implemented the behavior was with a click handler).

**Comment by suzmas** [comment]
Alrighty, I looked into it. So the active state toggles between true/false. When you click another panel without closing the last one, the active state is still set to true- so it sets active to false, when really, you want it to remain active.

**Comment by sslampa** [comment]
I'm sorry, Suzan. I can't get this to work completely. I uploaded a `bugs` branch of my closest iteration. I dont know what else to do from there

**Comment by suzmas** [comment]
K I'll check it out right now and we can figure it out!
