### ISSUE TITLE
Address in Events View

### ISSUE THREAD

**Issue by suzmas** [suzmas/react-rails#183]
Might make sense to list address in event panel?

**Comment by sslampa** [comment]
Yea that seems good

**Comment by sslampa** [comment]
![selection_028](https://user-images.githubusercontent.com/11300367/27254956-8f8229b8-5348-11e7-8581-b282cb6bbdc1.png)

That's how the Event panel looks with #189.

**Comment by suzmas** [comment]
This looks great! Merging.
