### ISSUE TITLE
UI Decisions

### ISSUE THREAD

**Issue by suzmas** [suzmas/react-rails#192]
### colors
  -bkg should be #f5f5f5
  

### navbar
  -double decker navbar
  -input and logo on level 1
  -addtl filters, clear button, map/list toggle on level 2
  -time filter has a default time displayed- button clicked to change
  -auto sort things by closest to time.now
  -icon for reset button

### Input boxes / most buttons
  -remove border
  -change location icon
  -placeholder
  -place/event select before search&location inputs
  -icon font size ++
  
### panels
  -panel bkg should be white
  -increase header size
  -website under header (small) --> change column phone_number to website
  -display 10 panels
  -prev/next should be icons instead of text

### map
  -markers should have popup open on active panel
  -increase size on active --> no color change

### other stuff
  -font is ugly

**Comment by sslampa** [comment]
If you dont how I did the scroll bar, I can easily remove it. You can also laugh at me if it's that bad.
