### ISSUE TITLE
Current Location Doesn't Work on Heroku

### ISSUE THREAD

**Issue by suzmas** [suzmas/react-rails#231]
getCurrentLocation() doesn't allow insecure origins, so we can't use it unless we serve over https

**Comment by sslampa** [comment]
I'm pretty sure it's because we're outside of SD that current location isn't working. I dont know if you want to fix it so that there is no range or what. Let me know what you think.

**Comment by sslampa** [comment]
I was able to find the https link for our map tiles, so the https warning shouldnt show up anymore. Sorry I keep blowing up your email :P
