### ISSUE TITLE
Button styling

### ISSUE THREAD

**Issue by sslampa** [suzmas/react-rails#66]
I added buttons for the filtering. Obviously, if you think the styling/icons should change, change it. In its current state, both buttons would need a "clicked" style.

**Comment by suzmas** [comment]
Looks like you can only select one at a time. I'll check it out but if there was a reason for doing that lmk. :-)

**Comment by sslampa** [comment]
Right now, there shouldn't be any kind of clicked style so maybe you're seeing the focus that's created by bootstrap buttons

**Comment by suzmas** [comment]
Just bare with me here Stephen
