### ISSUE TITLE
Formatting / UI Issues

### ISSUE THREAD

**Issue by suzmas** [suzmas/react-rails#95]
## UI Issues:

- [x] Map format on sm & xs screens
- [x] Change hamburger icon to something indicating additional filters
- [x] Location markers
- [x] Resize location markers -> active/inactive sizes do not match
- [x] Change color of active marker- it does not stand out as yellow color- blends into map sometimes
- [x] Other ugly things :-D
- [ ] Remove button select blue highlight- change to... something... _anything_ else
- [ ] Create proper logo and favicon
- [x] Work on EventPanel inner content styling
- [ ] Come up with a better / more crisp / more interesting color scheme
- [x] Time select drop-downs do not fit container- leave a lot of extra space
- [x] Keep search & location input in navbar on all screensizes
- [x] Increase EventPanel "hours string" font size --> should be focus of attention

**Comment by sslampa** [comment]
> Remove button select blue highlight- change to... something... anything else

I agree that the active highlighting doesn't look great, but I'm not sure if how to change this. The active state still needs to be seen for accessibility, but I'm curious if you have any other thoughts

**Comment by sslampa** [comment]
> Change hamburger icon to something indicating additional filters

Tell me what you think of the new hamburger menu. I just changed the icon to the standard filter icon and then styled the button to be a bit more consistent with the boolean buttons
